# Generated by Django 5.2.1 on 2025-06-01 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atrakcje', '0001_initial'),
        ('konta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanZwiedzania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('opis', models.TextField(blank=True)),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
                ('data_modyfikacji', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('S', 'Szkic'), ('A', 'Aktywny'), ('Z', 'Zakończony'), ('X', 'Zarchiwizowany')], default='S', max_length=1)),
                ('is_public', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Plan zwiedzania',
                'verbose_name_plural': 'Plany zwiedzania',
                'ordering': ['-data_utworzenia'],
            },
        ),
        migrations.CreateModel(
            name='EtapPlanu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('kolejnosc', models.PositiveIntegerField()),
                ('opis', models.TextField(blank=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapy', to='plany.planzwiedzania')),
            ],
            options={
                'verbose_name': 'Etap planu',
                'verbose_name_plural': 'Etapy planu',
                'ordering': ['kolejnosc'],
                'unique_together': {('plan', 'kolejnosc')},
            },
        ),
        migrations.CreateModel(
            name='ElementEtapu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolejnosc', models.PositiveIntegerField()),
                ('planowana_data', models.DateTimeField()),
                ('czas_wizyty', models.PositiveIntegerField(help_text='Czas w minutach')),
                ('czas_dojazdu', models.PositiveIntegerField(blank=True, help_text='Czas w minutach', null=True)),
                ('uwagi', models.TextField(blank=True)),
                ('atrakcja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atrakcje.atrakcja')),
                ('etap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementy', to='plany.etapplanu')),
            ],
            options={
                'verbose_name': 'Element etapu',
                'verbose_name_plural': 'Elementy etapu',
                'ordering': ['kolejnosc'],
                'unique_together': {('etap', 'kolejnosc')},
            },
        ),
        migrations.CreateModel(
            name='PlanUzytkownika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jest_wlascicielem', models.BooleanField(default=True)),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='konta.user')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plany.planzwiedzania')),
            ],
            options={
                'verbose_name': 'Plan użytkownika',
                'verbose_name_plural': 'Plany użytkowników',
                'unique_together': {('uzytkownik', 'plan')},
            },
        ),
    ]
