# Generated by Django 5.2.1 on 2025-06-07 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plany', '0002_planpodglad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elementetapu',
            name='uwagi',
        ),
    ]
