# Generated by Django 5.2.1 on 2025-06-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plany', '0003_remove_elementetapu_uwagi'),
    ]

    operations = [
        migrations.AddField(
            model_name='planzwiedzania',
            name='adres_startowy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
