# Generated by Django 5.2.1 on 2025-06-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plany', '0004_planzwiedzania_adres_startowy'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapplanu',
            name='adres_startowy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
