# Generated by Django 5.2.1 on 2025-06-01 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100, unique=True)),
                ('ikona', models.CharField(blank=True, max_length=30)),
                ('opis', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Kategoria',
                'verbose_name_plural': 'Kategorie',
            },
        ),
        migrations.CreateModel(
            name='RodzajBiletu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('opis', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Rodzaj biletu',
                'verbose_name_plural': 'Rodzaje biletów',
            },
        ),
        migrations.CreateModel(
            name='Lokalizacja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miasto', models.CharField(max_length=50)),
                ('ulica', models.CharField(max_length=100)),
                ('numer_budynku', models.CharField(max_length=10)),
                ('kod_pocztowy', models.CharField(max_length=10)),
                ('szerokosc_geo', models.FloatField(blank=True, null=True)),
                ('dlugosc_geo', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Lokalizacja',
                'verbose_name_plural': 'Lokalizacje',
                'db_table': 'Lokalizacja',
                'unique_together': {('miasto', 'ulica', 'numer_budynku')},
            },
        ),
        migrations.CreateModel(
            name='Atrakcja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200, unique=True)),
                ('opis', models.TextField()),
                ('minimalny_wiek', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kategoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='atrakcje.kategoria')),
                ('lokalizacja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='atrakcje.lokalizacja')),
            ],
            options={
                'verbose_name': 'Atrakcja',
                'verbose_name_plural': 'Atrakcje',
            },
        ),
        migrations.CreateModel(
            name='Cennik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cena', models.DecimalField(decimal_places=2, max_digits=8)),
                ('waluta', models.CharField(default='PLN', max_length=3)),
                ('ważny_od', models.DateField()),
                ('ważny_do', models.DateField(blank=True, null=True)),
                ('atrakcja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ceny', to='atrakcje.atrakcja')),
                ('rodzaj_biletu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='atrakcje.rodzajbiletu')),
            ],
            options={
                'verbose_name': 'Cennik',
                'verbose_name_plural': 'Cenniki',
                'ordering': ['-ważny_od'],
            },
        ),
        migrations.CreateModel(
            name='StatusAtrakcji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('D', 'Dostępna'), ('N', 'Niedostępna'), ('R', 'W remoncie'), ('Z', 'Zamknięta')], max_length=1)),
                ('data_zmiany', models.DateTimeField(auto_now_add=True)),
                ('komentarz', models.TextField(blank=True)),
                ('atrakcja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statusy', to='atrakcje.atrakcja')),
            ],
            options={
                'verbose_name': 'Status atrakcji',
                'verbose_name_plural': 'Statusy atrakcji',
                'ordering': ['-data_zmiany'],
            },
        ),
        migrations.CreateModel(
            name='ZdjecieAtrakcji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zdjecie', models.ImageField(upload_to='atrakcje/')),
                ('is_glowne', models.BooleanField(default=False)),
                ('opis', models.CharField(blank=True, max_length=200)),
                ('atrakcja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zdjecia', to='atrakcje.atrakcja')),
            ],
            options={
                'verbose_name': 'Zdjęcie atrakcji',
                'verbose_name_plural': 'Zdjęcia atrakcji',
            },
        ),
        migrations.CreateModel(
            name='GodzinyOtwarcia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dzien_tygodnia', models.CharField(choices=[('1', 'Poniedziałek'), ('2', 'Wtorek')], max_length=1)),
                ('godzina_otwarcia', models.TimeField()),
                ('godzina_zamkniecia', models.TimeField()),
                ('czy_otwarte', models.BooleanField(default=True)),
                ('atrakcja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='godziny_otwarcia', to='atrakcje.atrakcja')),
            ],
            options={
                'verbose_name': 'Godziny otwarcia',
                'verbose_name_plural': 'Godziny otwarcia',
                'unique_together': {('atrakcja', 'dzien_tygodnia')},
            },
        ),
    ]
