# Generated by Django 5.2.1 on 2025-06-01 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atrakcje', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atrakcja',
            name='lokalizacja',
        ),
        migrations.AddField(
            model_name='lokalizacja',
            name='atrakcja',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lokalizacja', to='atrakcje.atrakcja'),
        ),
    ]
