# Generated by Django 5.2.1 on 2025-06-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atrakcje', '0002_remove_atrakcja_lokalizacja_lokalizacja_atrakcja'),
    ]

    operations = [
        migrations.AddField(
            model_name='atrakcja',
            name='czas_zwiedzania',
            field=models.PositiveIntegerField(blank=True, help_text='Szacowany czas zwiedzania (w minutach)', null=True),
        ),
    ]
