# Generated by Django 5.2.1 on 2025-06-07 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atrakcje', '0004_cennikstatystyki'),
    ]

    operations = [
        migrations.CreateModel(
            name='CennikStatystykiMV',
            fields=[
                ('atrakcja', models.OneToOneField(db_column='atrakcja_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='atrakcje.atrakcja')),
                ('min_cena', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_cena', models.DecimalField(decimal_places=2, max_digits=8)),
                ('avg_cena', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'MV_CENNIK_STATYSTYKI',
                'managed': False,
            },
        ),
    ]
