# Generated by Django 5.2.1 on 2025-06-07 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atrakcje', '0005_cennikstatystykimv'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CennikStatystyki',
        ),
    ]
