# Generated by Django 5.2.1 on 2025-06-08 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atrakcje', '0008_cennikstatystykimv_delete_cennikstatystyki'),
    ]

    operations = [
        migrations.AlterField(
            model_name='godzinyotwarcia',
            name='dzien_tygodnia',
            field=models.CharField(choices=[('1', 'Poniedziałek'), ('2', 'Wtorek'), ('3', 'Środa'), ('4', 'Czwartek'), ('5', 'Piątek'), ('6', 'Sobota'), ('7', 'Niedziela')], max_length=1),
        ),
    ]
